var soundboardItems = [{
	"text": "Cause-youve-got-ebola!.mp3",
	"src": "Cause-youve-got-ebola!.mp3",
	"id": "Cause-youve-got-ebola!.mp3"
}, {
	"text": "Charisma-and-Je-Ne-Sais-Quoi-1.mp3",
	"src": "Charisma-and-Je-Ne-Sais-Quoi-1.mp3",
	"id": "Charisma-and-Je-Ne-Sais-Quoi-1.mp3"
}, {
	"text": "Charisma-and-Je-Ne-Sais-Quoi-2.mp3",
	"src": "Charisma-and-Je-Ne-Sais-Quoi-2.mp3",
	"id": "Charisma-and-Je-Ne-Sais-Quoi-2.mp3"
}, {
	"text": "Council-bollocks!.mp3",
	"src": "Council-bollocks!.mp3",
	"id": "Council-bollocks!.mp3"
}, {
	"text": "Dont-Touch-What-You-Cant-Afford-1.mp3",
	"src": "Dont-Touch-What-You-Cant-Afford-1.mp3",
	"id": "Dont-Touch-What-You-Cant-Afford-1.mp3"
}, {
	"text": "Dont-Touch-What-You-Cant-Afford-2.mp3",
	"src": "Dont-Touch-What-You-Cant-Afford-2.mp3",
	"id": "Dont-Touch-What-You-Cant-Afford-2.mp3"
}, {
	"text": "Dont-Touch-What-You-Cant-Afford-3.mp3",
	"src": "Dont-Touch-What-You-Cant-Afford-3.mp3",
	"id": "Dont-Touch-What-You-Cant-Afford-3.mp3"
}, {
	"text": "Ebola!-1.mp3",
	"src": "Ebola!-1.mp3",
	"id": "Ebola!-1.mp3"
}, {
	"text": "Forward-Slash-Bollocks.mp3",
	"src": "Forward-Slash-Bollocks.mp3",
	"id": "Forward-Slash-Bollocks.mp3"
}, {
	"text": "He-cant-spell-work.mp3",
	"src": "He-cant-spell-work.mp3",
	"id": "He-cant-spell-work.mp3"
}, {
	"text": "I-dont-know-do-i.mp3",
	"src": "I-dont-know-do-i.mp3",
	"id": "I-dont-know-do-i.mp3"
}, {
	"text": "I-dont-know-what-it-means.mp3",
	"src": "I-dont-know-what-it-means.mp3",
	"id": "I-dont-know-what-it-means.mp3"
}, {
	"text": "Jaeger-Bomb-1.mp3",
	"src": "Jaeger-Bomb-1.mp3",
	"id": "Jaeger-Bomb-1.mp3"
}, {
	"text": "Leave-It-1.mp3",
	"src": "Leave-It-1.mp3",
	"id": "Leave-It-1.mp3"
}, {
	"text": "Leave-It-2.mp3",
	"src": "Leave-It-2.mp3",
	"id": "Leave-It-2.mp3"
}, {
	"text": "Leave-It-3.mp3",
	"src": "Leave-It-3.mp3",
	"id": "Leave-It-3.mp3"
}, {
	"text": "Leave-It-4.mp3",
	"src": "Leave-It-4.mp3",
	"id": "Leave-It-4.mp3"
}, {
	"text": "Leave-It-5.mp3",
	"src": "Leave-It-5.mp3",
	"id": "Leave-It-5.mp3"
}, {
	"text": "Leave-It-6.mp3",
	"src": "Leave-It-6.mp3",
	"id": "Leave-It-6.mp3"
}, {
	"text": "Leave-it-alone.mp3",
	"src": "Leave-it-alone.mp3",
	"id": "Leave-it-alone.mp3"
}, {
	"text": "Leave-it-cos-i-got-ebola.mp3",
	"src": "Leave-it-cos-i-got-ebola.mp3",
	"id": "Leave-it-cos-i-got-ebola.mp3"
}, {
	"text": "Leave-it-cos-you-got-ebola.mp3",
	"src": "Leave-it-cos-you-got-ebola.mp3",
	"id": "Leave-it-cos-you-got-ebola.mp3"
}, {
	"text": "Oh-My-God-1.mp3",
	"src": "Oh-My-God-1.mp3",
	"id": "Oh-My-God-1.mp3"
}, {
	"text": "Oh-My-God-2.mp3",
	"src": "Oh-My-God-2.mp3",
	"id": "Oh-My-God-2.mp3"
}, {
	"text": "Oh-feck-it.mp3",
	"src": "Oh-feck-it.mp3",
	"id": "Oh-feck-it.mp3"
}, {
	"text": "Oliver-1.mp3",
	"src": "Oliver-1.mp3",
	"id": "Oliver-1.mp3"
}, {
	"text": "Oliver-2.mp3",
	"src": "Oliver-2.mp3",
	"id": "Oliver-2.mp3"
}, {
	"text": "Up-There-Thinking-Down-There-Dancing.mp3",
	"src": "Up-There-Thinking-Down-There-Dancing.mp3",
	"id": "Up-There-Thinking-Down-There-Dancing.mp3"
}, {
	"text": "Wetting-Yourself.mp3",
	"src": "Wetting-Yourself.mp3",
	"id": "Wetting-Yourself.mp3"
}, {
	"text": "What-a-loada-bollocks.mp3",
	"src": "What-a-loada-bollocks.mp3",
	"id": "What-a-loada-bollocks.mp3"
}, {
	"text": "Whores-Knickers.mp3",
	"src": "Whores-Knickers.mp3",
	"id": "Whores-Knickers.mp3"
}, {
	"text": "Yaman!-1.mp3",
	"src": "Yaman!-1.mp3",
	"id": "Yaman!-1.mp3"
}, {
	"text": "Yaman!-2.mp3",
	"src": "Yaman!-2.mp3",
	"id": "Yaman!-2.mp3"
}, {
	"text": "Yaman!-3.mp3",
	"src": "Yaman!-3.mp3",
	"id": "Yaman!-3.mp3"
}, {
	"text": "Yello!-1.mp3",
	"src": "Yello!-1.mp3",
	"id": "Yello!-1.mp3"
}, {
	"text": "You-tart.mp3",
	"src": "You-tart.mp3",
	"id": "You-tart.mp3"
}];

exports.soundboardItems = soundboardItems;